config/routes.rb
Rails.application.routes.draw do

 
  resources :articles
 
  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	require 'ContentHelper'
end

app/models/element.rb
class element
	def initialize(title = "Title", text = "text" )
		@title = title
		@text = text
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController 
	require 'ContentHelper'
	helper ContentHelper

	require 'json'	


    def new
    	puts "NEW"	  	

    end

    def edit
    	puts "Edit"

		@article = Article.new
    	@article.title = params[:id] + "." + params[:format]


	  	puts(@article.title)

    end


	def show
require 'rest_client'
		puts "SHOW"	

		major = params[:id]
	  	minor = params[:format]

     	article_resp = ContentHelper.get_content("#{major}.#{minor}")

     	puts(article_resp)

	  	paresed_article = JSON(article_resp)

		@article = Article.new
		@article.title = paresed_article["contentData"]["title"]
		@article.text = paresed_article



	end

	def create
		puts "CREATE"	
	  @article = Article.new(article_params)
	 
	  @article.save
	  redirect_to @article
	end
	
	def renderActionInOtherController(controller,action,params)
	  controller.class_eval{
	    def params=(params); @params = params end
	    def params; @params end
	  }
	  c = controller.new
	  c.request = @_request
	  c.response = @_response
	  c.params = params
	  c.send(action)
	  c.response.body
	end


	private
	  	def article_params
	    	params.require(:article).permit(:title, :text)
  		end




end

app/controllers/image.rb
class _ImageController < ApplicationController
    def show
    	puts "ImageController"
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  puts "Welcome"

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contentHelper.rb
module ContentHelper
  def self.get_content(str)
  	puts "getContent"
  	response = RestClient.post('http://localhost:8080/onecms/security/token?format=json',
  			{'username' => 'sysadmin',
  			 'password' => 'sysadmin'
  			}.to_json,
			:content_type => 'application/json')

  	paresed_response = JSON(response)
  	token = paresed_response["token"]


  	url = "http://localhost:8080/onecms/content/contentid/#{str}?format=json"
  	puts url

  	response = RestClient.get(url,
		:x_auth_token => token)


    return response
  end

  def self.get_content2(str)
    puts "getContent22"

    puts "test"
    str = str.slice(10,str.length)
    puts "string slice: " + str

    response = RestClient.post('http://localhost:8080/onecms/security/token?format=json',
        {'username' => 'sysadmin',
         'password' => 'sysadmin'
        }.to_json,
      :content_type => 'application/json')

    paresed_response = JSON(response)
    token = paresed_response["token"]


    url = "http://localhost:8080/onecms/content/contentid/#{str}?format=json"
    puts url

    response = RestClient.get(url,
    :x_auth_token => token)


    return response
  end

  def self.get_value_from_json(str, key)
    paresed_str = JSON(str)
    return paresed_str[key]

  end


  def get_content(str)
    return ContentHelper.get_content(str)
  end

  def get_content2(str)
    return ContentHelper.get_content2(str)
  end

  def get_value_from_json(str, key)
    return ContentHelper.get_value_from_json(str, key)
  end


  def getHelp()
  	return "HELP"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.hrml.erb
<div>
	<%= get_value_from_json(article, "contentData")["title"] %>

	<div>
		<%= get_content2(@article.text["contentData"]["images"][0]) %>
		<%= render partial: "image", locals: {image: get_content2(get_value_from_json(article, "contentData")["images"][0])} %>
	</div>
</div>

app/views/articles/_article.html.erb
<div>
	<%= puts(article) %>
	<%= puts(get_value_from_json(article, "contentData")["title"]) %>

	<div>
		<%= render partial: "image", locals: {image: get_content2(get_value_from_json(article, "contentData")["images"][0])} %>
	</div>
</div>

app/views/articles/_header.html.erb
<%= puts("Rendering header") %>

<div class="header">
	<span>
		<h3>RubyPoly                  Bussiness	Science		Sport</h3>
	</span>
</div>

app/views/articles/_image.html.erb
<img src="<%= "http://127.0.0.1:8080\/image\/" + get_value_from_json(image, "versionId") + "\/image.jpg?w=750" %>"/ >
<p class="meta">
	<%= get_value_from_json(image, "contentData")["description"] %>
	<span class="byline"><%= get_value_from_json(image, "contentData")["byline"] %></span>
</p>

<p>
  <strong>Content:</strong>
  <%= image %>
</p>

app/views/articles/_left.html.erb
<div>

	<%= render partial: "list_element", collection: get_value_from_json(list, "contentData")["default"]["list"], as: :element %>
	
</div>

app/views/articles/_list_element.erb
<div>
<%= render partial: "teaser", locals: {article: get_content2(element["contentId"]) }%>
</div>

app/views/articles/_right.html.erb
<div>
<p>Menu</p>
<p>Menu</p>
<p>Menu</p>
<p>Menu</p>
<p>Menu</p>
<p>Menu</p>


</div>

app/views/articles/_teaser.html.erb
<div>
	<a href="/articles/1/edit.122" title="">
	<%= get_value_from_json(article, "contentData")["title"] %>
	</a>
</div>

app/views/articles/edit.html.erb
<div class="container-fluid">
	<div>
		<%= render partial: "header" %>
	</div>
	<div class="row">
		<div class="col-md-8">
			<div>
				<%= puts("getarticle: " + @article.title) %>
				<%= render partial: "article", locals: {article: get_content(@article.title)} %>
			</div>	
		</div>
		<div class="col-md-4">
			<%= render partial: "right" %>
		</div>
	</div>

</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>	

app/views/articles/show.html.erb
<div class="container-fluid">
	<div>
		<%= render partial: "header" %>
	</div>
	<div class="row">
		<div class="col-md-8">
			<div>
				<%= render partial: "article", locals: {article: get_content("1.121")} %>
			</div>	
		</div>
		<div class="col-md-4">
			<%= render partial: "right" %>
		</div>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>
<p></p>